댓글 작성자가 admin일때 디자인 변경 / comment container자체 레이아웃 조정
lumyjuwon/elaina-blog pull request #26
Opened 2021-07-26 17:43 UTC by loftol

theme부분도 약간 수정했는데 conflict가 생길 수도 있을까요?
그 밖에 CommentBox.tsx 파일에서 컴포넌트 호출명에 에러가 있어서 일단 변경해둔 것도 있습니다.'
'에러 처리'라는 커밋에 변경사항이 있으니 확인하고 의도된 부분이었다면 알려주면 다시 고치겠습니다.

2021-07-26 18:03 UTC, Ikalli commented
server쪽에 package관련 파일들이 커밋되어있는대.. 이부분 없애주세요ㅜ

2021-07-27 01:48 UTC, Ikalli commented
이런식으로 댓글 쓰는거랑, 댓글만 양옆으로 `1rem` 정도 들어가게 할 수 있나? Comment글자나, 댓글 수는 그대로 두고ㅇㅇ

![제목 없음](https://user-images.githubusercontent.com/16658067/127081945-ebb02d63-c9c2-4cf2-94b3-dfea8e955fc2.png)

2021-07-27 01:53 UTC, Ikalli commented
그리고 코드에 Prettier가 적용 안되고 있는 것 같은데, workspace에서 작업하는중인지랑 Prettier 제대로 작동하고 있는지 확인좀!

2021-07-27 02:38 UTC, Ikalli requested changes
일단 코드리뷰 올려둠!
해결하면 Resolve Conversation 눌러서 없애주면 좋을듯

2021-07-27 02:38 UTC, Ikalli commented on client/src/components/pages/post/comment/box/CommentDetail.tsx
> +}));
CSS Ordering Rule 참고해서 순서만 바꿔주십셔

2021-07-27 02:38 UTC, Ikalli commented on client/src/components/pages/post/comment/writer/Writer.tsx
>    alignItems: 'center',
relative, absolute를 쓰는것 보다는, `flex`로 쓰는게 좀 더 나을 듯 함!
`ButtonContainer` 에 `display: 'flex'`를 주고, `justifyContent: flex-end`로 하면, `SubmitButton`은 자동으로 오른쪽 정렬이 될거임

2021-07-27 02:38 UTC, Ikalli commented on client/src/components/pages/post/comment/box/CommentDetail.tsx
> +  marginRight: '.7rem'
CSS Ordering Rule 참고해서 순서만 바꿔주십셔

2021-07-27 02:38 UTC, Ikalli commented on client/src/components/pages/post/comment/box/CommentDetail.tsx
> +
CSS Ordering Rule 참고해서 순서만 바꿔주십셔

2021-07-27 02:38 UTC, Ikalli commented on client/src/components/pages/post/comment/writer/Writer.tsx
>    alignItems: 'center',
아마 이런 정렬문제는 대부분 flex로 해결이 될겁니당ㅋㅋㅋ
이럴때는 `float`, `position` 프로퍼티는 지양하는걸로!

2021-07-27 04:30 UTC, Ikalli commented on client/src/components/pages/post/comment/box/CommentDetail.tsx
> +  overflow: 'hidden'
`overflow` 프로퍼티가 필요한 이유는??

2021-07-27 07:38 UTC, loftol commented
![comment_design_dark](https://user-images.githubusercontent.com/60003939/127115031-c9d45870-b5e7-4720-b4ba-8676246ad297.PNG)
![comment_design_light](https://user-images.githubusercontent.com/60003939/127115051-07224f97-4703-4920-8346-dcc4421c6033.PNG)
최근 디자인 변경과 함께 댓글 쓰는 칸과 댓글 칸 좌우 여백 1rem씩 늘렸습니다.

2021-07-27 10:11 UTC, Ikalli commented
댓글 쓰는게 가운데 정렬이 안되있는것 같음..!

2021-07-27 10:15 UTC, Ikalli approved these changes

2021-07-27 10:15 UTC, Ikalli commented on client/src/components/pages/post/comment/CommentElement.tsx
> +  borderTop: `3px solid ${props.theme.borderColor}`,
여기의 border는 2px이 적당해보인다.. 3px은 너무 두꺼운듯

2021-07-27 10:15 UTC, Ikalli commented on client/src/components/pages/post/comment/ReplyElement.tsx
> +  borderLeft: '3px solid #727272'
여기는 3px 유지합니다 굳굳

2021-07-27 12:19 UTC, loftol commented
![comment_design_3_light](https://user-images.githubusercontent.com/60003939/127152330-17d07bad-625b-4571-a8a8-280b387269ad.PNG)
![comment_design_3_dark](https://user-images.githubusercontent.com/60003939/127152355-26e54f27-68d9-4ae8-b65a-772b80c16958.PNG)

띄어쓰기 없이 무한 입력 시 화면 오른쪽으로 내용물이 뚫고 넘어가기에 그냥 overflow-wrap을 anywhere로 지정해 버렸습니다.
가운데 정렬도 확인해 놨습니다.

2021-07-27 13:43 UTC, Ikalli commented
음... 가운데 정렬이 안되는데.....
전체적으로 오른쪽으로 가 있다고 해야하나??.,. 윤곽선 그리면 잘 보일거임!
+ Reply는 Comment보단 작게 만드는게 좋아보임!

진짜 다 완벽하니까 컨테이너(빨간 윤곽선)는 가운데로 정렬시키고, Reply는 크기(width)를 초록색 윤곽선에 맞추는거만 하면...ㅠㅠㅠㅠ 감사할것 같습니돠ㅜㅜ

![image](https://user-images.githubusercontent.com/16658067/127164326-a07d92cb-c76a-4ead-a9b3-7dd809e08698.png)
![image](https://user-images.githubusercontent.com/16658067/127164375-b1eea133-6aa6-4aed-9414-41a27b72600a.png)

2021-07-27 23:28 UTC, loftol commented
![comment_design_4_dark](https://user-images.githubusercontent.com/60003939/127239972-5c963556-54e1-47f9-b84a-55bcf30266f2.PNG)
![comment_design_4_light](https://user-images.githubusercontent.com/60003939/127239985-03fa1a57-2baf-4411-b03b-8b56f85e510f.PNG)
reply container 전체를 녹색칸에 맞춰달라는 걸로 해석해서 크기를 줄였습니다.
(해당 과정에서 width를 100%로 하고 margin을 같이 넣으면 왠지 margin을 뚫고 내용물이 오른쪽으로 치우쳐지기에 width를 95%로 바꾸는걸로 해결했는데 더 좋은 방법이 있을까요?)
light 모드에서 배경색을 더 연하게 바꿨는데 앞에 거랑 비교해서 더 좋은 쪽으로 결정하겠습니다.

2021-07-28 02:15 UTC, Ikalli commented
`width: 95%` 가 나아보임ㅋㅋ `width: 100%` 에다가 margin을 더하면 길이가 100% + margin이 되서 뚫고나오니ㅋㅋ 굳굳

2021-07-28 02:17 UTC, merged