Resize textarea
lumyjuwon/elaina-blog pull request #28
Opened 2021-07-29 16:28 UTC by loftol

![auto_resize](https://user-images.githubusercontent.com/60003939/127529646-83200e2d-b085-491a-a92d-d3a0c6f02540.PNG)
변수, 함수 선언 및 호출 순서 최대한 맞춰놨습니다.
prop도 순서가 정해져 있는지는 모르겠는데 보기 예쁘게 대충 맞춰놨습니다.

2021-07-29 16:45 UTC, Ikalli requested changes

2021-07-29 16:45 UTC, Ikalli commented on client/src/components/pages/post/comment/writer/Writer.tsx
> +  }, []);
1. useCallback이 여기선 의미가 없어보임. Memoization 상황 때 useCallback을 사용하면 좋은데, 여긴 그런 상황이 아니여서.. 오히려 useCallback이 방해가 됩니당
2. 이 함수가 호출되면 우리 눈엔 길이가 늘어난걸로 보이겠지만, 잘 보면 항상 height가 `5rem` 으로 갔다가 늘어나게 되는거라 수정해야될 것 같음. 텍스트가 넘쳤을 때 길이를 늘리는 방식으로 생각해보면 좋을 듯!

2021-07-29 16:45 UTC, Ikalli commented on client/src/components/pages/post/comment/writer/Writer.tsx
> +        onInput={resizeHeightHandler}
리액트에서는 onChange, onInput 이 똑같은걸로 알고 있습니당. 리팩토링을 하자면 onChange 하나에 합치는걸로 하면 좋을듯
```ts
function onChange(e: React.ChangeEvent<HTMLTextAreaElement>) {
  /*
    TODO: 텍스트가 넘쳤다면, 길이 늘리기
  */
  setComment(e.target.value);
}

return <Editor onChange={onChange} />
```

2021-07-29 16:51 UTC, Ikalli commented on client/src/components/pages/post/comment/writer/Writer.tsx
> +        onInput={resizeHeightHandler}
리액트 하면서 onInput은 사용은 거의 안한듯.. 차이는 없어보이는대 대부분의 경우는 onChange로 사용!

React onChange vs onInput은 아래 링크 참조
https://stackoverflow.com/questions/38256332/in-react-whats-the-difference-between-onchange-and-oninput

2021-07-29 17:58 UTC, loftol commented on client/src/components/pages/post/comment/writer/Writer.tsx
> +  }, []);
1. useCallback은 지우고 돌려도 잘 돌아가는 거 확인했음.

2. 관련해서는 좀 힌트가 필요해서 그런데,
현재 내가 구현한 방식이 글자들의 총 높이를 textHeight라고 하면
(textHeight는 따로 구한 값은 아니고 이런게 있다고 가정하는 건데)

글자가 넘쳤을 때 : textHeight === scrollHeight > height 인 상태가 돼서
scrollHeight > height 혹은 scrollHeight !== height (후자가 더 일반적이니까 후자를 쓰겠지만)
위의 둘중 하나로 if 문을 걸면 충분히 구현이 가능한데,

글자가 줄어들었을 때 : textHeight < scrollHeight === height 인 상태가 돼서
scrollHeight 와 height의 비교로는 어떻게 줄일만한 상황을 걸러내질 못하겠어

위 구현에서는 height에다가 minHeight을 넣어서 다시 글자가 넘친 상황으로 만들어서 해결하는 건데,
다른 방법이 있을까?

2021-07-29 18:10 UTC, loftol commented on client/src/components/pages/post/comment/writer/Writer.tsx
> +  }, []);
1. useCallback은 지우고 돌려도 잘 돌아가는거 확인했음.

2. 관련해서는 힌트가 필요해서 그런데,
실제로는 없는 변수지만,
총 text의 높이를 textHeight라고 하면

글자가 넘친경우 : textHeight === scrollHeight > height가 되면서
scrollHeight !== height (혹은 scrollHeight > height) 같은 if 문을 이용해 제어할 수 있고,
실제로 이 방법으로 textarea가 늘어나는 것도 확인을 했어.

글자가 줄어든 경우 : textHeight < scrollHeight === height가 되면서
if 문을 이용해 제어할 방법이 따로 없더라고
이것도 backspace로 내용을 지워도 textarea가 줄어들지 않는 걸 확인했고.

위의 코드에서는 height를 일단 5rem으로 줄임으로 글자가 넘친 경우로 바꿔서 
scrollHeight를 textHeight값으로 같게 만들어서 해결하는데,
저렇게 하지 않고 textarea를 줄이는 방법을 못 찾겠네..

아래에 써 놓은 대로 onInput은 버리고 onChange로 바꿔둘게

2021-07-30 02:51 UTC, loftol commented on client/src/components/pages/post/comment/writer/Writer.tsx
> +  }, []);
1. useCalback 없이도 잘 돌아가는 거 확인했음.
2. 는 힌트가 좀 필요해..

텍스트가 넘쳤을 때 길이를 늘리는 건 어렵지 않은데, 줄었을 때 길이가 줄어드는 걸 같이 구현 하려니 일단 5rem으로 갔다가 늘어나는 게 가장 적절한 것 같아.

높이에 상수값을 추가/제거 하는 방식으로 처리하기에는 여러 줄이 한번에 늘어나거나 한번에 줄어드는 경우 같은 것도 고려해야 해서 (복사 붙여넣기/여러줄 선택 후 삭제) 그건 불가능 하고,

그냥 scrollHeight로 height를 바꾸자니 덧글 본문 내용의 총 높이를 textHeight라고 하면
넘쳤을 때 : textHeight === scrollHeight > height 가 돼서 (사실 정확히 같지는 않음)
구현 가능하지만

줄었을 때 : textHeight < scrollHeight === height 가 돼서 (이것도 정확히 같지는 않음)
textHeight를 따로 구하지 않는 한 height를 textHeight에 맞게 줄일 방법이 따로 없는 것 같아.

위 코드에서는 height를 5rem으로 줄여서 넘쳤을 때 상황으로 바꾼 다음에 다시 scrollHeight로 바꿔서 해결한건데,
나로서는 다른 방법은 잘 모르겠네..

마지막으로 onInput은 없애고 onChange로 잘 통합시켜놨어.
해결한 부분만 따로 커밋해서 올릴게

2021-07-30 04:53 UTC, Ikalli commented on client/src/components/pages/post/comment/writer/Writer.tsx
> +  }, []);
음... 내가 휴가중이라 잘 못보긴 하지만, height로 접근하는거 말고 rows로 접근해보는거 어떰? textarea에 attribute에 rows라는게 있는데, 기존에 css minHeight는 주석처리하고... 예를들면 `<textarea row={3} />` 이렇게 하면 3행에 맞는 높이로 textarea 높이가 맞춰짐

autosize textarea관련 모듈이 있는데.. 모듈을 설치하긴 좀 아까우니 모듈을 뜯어보면 rows로 접근한 모듈이 있더라고
전체 코드는 좀 어려울 수 있는데, `getHeight`, `resize` 함수 위주로 보면 될 듯 합니당
https://github.com/rpearce/react-expanding-textarea/blob/main/source/index.tsx

일단 링크들어가서 코드 한번 보고 안될거같으면 말하십셔! 일단 동작한다고 하니, 글자가 살짝 움직인다거나.. 이런 부자연스러운거만 없으면 merge합시당.

2021-07-30 04:57 UTC, Ikalli commented on client/src/components/pages/post/comment/writer/Writer.tsx
> +  }, []);
내가 올려준 코드를 너무 따라할 필요는 없어보이고, rows를 가지고 height를 구해보는 생각을 해보면... 어떻겠는지...ㅋㅋㅋ

https://rpearce.github.io/react-expanding-textarea/?path=/story/expandingtextarea--with-minimum-3-rows

저 코드의 데모판인데, 3행은 기본으로 되어있고, resize가 잘 되는거 봐선..

2021-07-30 17:40 UTC, loftol commented on client/src/components/pages/post/comment/writer/Writer.tsx
> +  }, []);
공부하는 겸 해서 그냥 올려준 코드를 최대한 그대로 적용 시켜봤습니다
코드가 120줄 -> 200줄이 돼버린 게 좀 걸리기도 하고..
textarea 흔들거리는 거 전혀 없고, submit시 리셋되는것도 잘되고 전부 잘되는데

사실 이 코드도 scrollHeight와 rows를 이용해 각각 계산한 뒤 더 큰 쪽으로 길이 변환 시키는 방식이었고,
scrollHeight를 제대로 이용하기 위해 92째 줄에서 마찬가지로 height에 0을 할당하는 걸 볼 수 있었습니다.

뭔가 꺼림칙해서 rows를 console을 찍어보니 textarea에서 뭘 입력해도 rows는 계속 0으로 일정한 걸(...) 볼 수 있었습니다. rows가 변하는 건 아마 textarea에서 입력하는 걸로 변하는 건 아닌 거 같더라고요

결국 이 코드도 변하는 부분은 scrollHeight를 이용한 부분 뿐이었고..
여기는 0px까지 줄었다가 다시 늘어나는 거라 사실 똑같은데 한 70줄 정도 더 긴 코드라는 걸 알았죠..

그래도 덕분에 useRef, useEffect, useCallback 같은 건 많이 공부했으니 그런 걸로 하고 커밋은 돌려놓고
확인하는대로 저는 resolve하겠습니다 ㅋㅋㅋㅋㅋ

2021-08-01 15:04 UTC, Ikalli requested changes
전체적으로 잘 짠 것 같은데, Ref 사용에 대해서 좀 더 문서를 읽거나 구글링하셔야 할듯...ㅠ

2021-08-01 15:04 UTC, Ikalli commented on client/src/components/pages/post/comment/writer/Writer.tsx
> +  const ref = (isForwardedRefFn || !forwardedRef ? internalRef : forwardedRef) as MutableRefObject<HTMLTextAreaElement>;
반복문 중첩이 심한데..
내가 볼 땐 이거 `forwardedRef()` 함수 쓰면 필요가 없어질 변수인것 같아

그리고 as문은 신중히!

2021-08-06 17:43 UTC, loftol commented
위 세 커밋에 대해 변명을 하자면, 예전 거로 롤백하는 과정에서 좀 실수가 있어서 헤맨게 아래 2개 커밋입니다.
![Animation](https://user-images.githubusercontent.com/60003939/128550175-da44e552-aa62-4521-8bd9-7595e1b81c61.gif)

현 변경사항은 add more on comment control 커밋의 설명을 참고하면 거의 다 써져 있지만,
1. delete 버튼을 누르면 modal 뜨던 거 없애버리고 댓글 창에 비밀번호 입력 창만 추가되도록 바꿨습니다.
2. 보다시피 delete 버튼을 누르면 reply를 볼 수 있는 버튼을 아예 없애버립니다.
    (버튼에 애니메이션이나 색상 / 배경 색상 추가하는 것도 나쁘지 않을 거 같아요)
3. edit 할 때 비밀번호 입력 칸 모양 변경을 하기는 했습니다. 마음에 안들 것 같으니 다시 좀 더 수정할 거고,
수정 방향성은 제시해주면 너무너무 좋죠.

코드에서 state중 몇 가지를 과감하게 없애버리고 추가한 것들이 있는데, 그 점도 눈여겨 봐주면 좋을 것 같아요.

그리고 영상에 안 넣었는데 (제일 중요한)삭제, 수정 잘 됩니다

2021-08-07 02:36 UTC, Ikalli commented
🎉👍😊

2021-08-07 02:40 UTC, merged