Post like
lumyjuwon/elaina-blog pull request #29
Opened 2021-08-19 17:28 UTC by loftol

![likey_1](https://user-images.githubusercontent.com/60003939/130115697-b205488b-42de-40b3-b2f4-b451eb2967f6.gif)

2021-08-20 13:41 UTC, Ikalli commented
음 디자인만 좀 바꿔줄 수 없나? 너무 작은데..
그리고 댓글 버튼 없애고 그냥 like버튼 크게 만들고 가운데 정렬시켜주셈

예시로 들긴 좀 그렇지만, 디시인사이드처럼 가운데에 크게 넣는것도 나쁘지 않은거같음
버튼 디자인은 좀 이쁘게 부탁드립니당! 엄지 말고 하트로 해도 괜찮고.. 암튼 이쁘장하게 여러개 참고하면 좋을듯

* Velog
![image](https://user-images.githubusercontent.com/16658067/130242197-b910bfec-72a3-4701-93d2-719fb532ad79.png)
* DC
![image](https://user-images.githubusercontent.com/16658067/130242255-f4e71158-67b4-4cbd-8137-5a71acf3c02b.png)

일단 댓글버튼 지우고, 좀 크고 이쁘게 만들어주면 좋을것같음 코드리뷰는 이거 디자인 바뀌면 그때 할게용

2021-08-20 15:56 UTC, loftol commented
![likey_2](https://user-images.githubusercontent.com/60003939/130260511-2b9df635-4951-4b15-982c-b73192fb2f8d.gif)
어떻게 해야 예쁠지 잘 모르겠어서.. 일단 대충 저렇게 만들어 둠

2021-08-20 18:19 UTC, Ikalli requested changes
으음 일단 UI는 괜찮아진것 같은데,
쿼리에서 약간 아쉽습니당... 클라이언트에서는 그냥 단지 증가시킬건지 감소시킬건지만 받아오고, 서버단에서 해결하는게 좋은대 지금은 서버에서 온 count를 바로 DB에 넣어버리는게 좀 걸림ㅠㅠ

리덕스는 전체적으로 잘 했슴! `payload`로 바꾸는거 해주면 좋을듯.

그리고 그냥 쿼리랑 리덕스 다 increase, decrease로 나눕시다! 합쳐져 있으니까 좀 별로인거같음

2021-08-20 18:19 UTC, Ikalli commented on server/src/graphql/post.ts
> +      }
클라이언트에서 받은 `likeCount`가 제대로 된건지 알 수 없음
기존 글에 A랑 B가 동시에 접속하고, A가 먼저 좋아요 누르고, B가 다음에 좋아요 누르면 +2 돼야 하는대 이러면 +1만 증가할거 같음

이러지말고 id값이랑 , 감소시킬건지, 증가시킬건지에 대해 인자를 받도록 하고, DB에 +1 ,-1씩만 하는걸로 하자
replace하는건 좋아보이지 않음

**쿼리는 명쾌한게 좋으니까 증가시키는 쿼리, 감소시키는 쿼리 따로 구분해도 좋을듯!**

그리고 return이 없어용... `Void` 말고 `Int!`로 하고, likeCount 반환해주는걸로 합시당

```ts
async increaseLikeCount(_: any, args: { id: number; }) {
    try {
      const clickedPost = await PostModel.findById(args.id);
      if (clickedPost) {
        clickedPost.likeCount += 1;
        await clickedPost.save();
      }
      
      return clickedPost.likeCount
    } catch (err) {
      throw err;
    }
  }
```

2021-08-20 18:19 UTC, Ikalli commented on server/src/graphql/post.ts
> +    editLikeCount(id: Int!, likeCount: Int!): Void
쿼리에 응답(response)이 없는게 굉장히 안좋은 패턴입니당... Void는 지양합시당ㅋㅋㅋㅋ 기존 Void도 바꿀 예정

2021-08-20 18:19 UTC, Ikalli commented on client/src/redux/post/type.ts
> +}
이렇게 말고 배열로 저장하면 안되나?

```ts
export interface PostState {
  likedPost: number[]; // or string[]
}
```
이러고 id를 배열에 넣으면 될거같은데... key: value쌍으로 꼭 안해도 될거같음

id가 배열에 있다: 이미 좋아요를 누른 글
없다: 아직 좋아요 누르지 않은 글

2021-08-20 18:19 UTC, Ikalli commented on client/src/redux/post/type.ts
> +}
객체보단 배열로 저장하는게 더 좋아 보입니당

2021-08-20 18:19 UTC, Ikalli commented on client/src/redux/post/action.ts
> +}
리덕스에서는 액션함수를 정의할 때 `payload`라는 객체를 관습적으로 사용함. 인자가 여러개일땐 한 객체로 묶고, `payload`로 정의해주는게 좋음

```ts
export function setLikedId(id: number, isLike: boolean) {
  return {
    type: ActionTypes.SetLikedId,
    payload: { id, isLike }
  };
}
```

https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers#designing-actions

2021-08-20 18:19 UTC, Ikalli commented on client/src/redux/post/reducer.ts
> +          [action.id]: action.isLike
`payload`를 사용하면 `action.payload.id`, `action.payload.isLike`로 각각 바꿔주십셩

2021-08-20 18:19 UTC, Ikalli commented on client/src/redux/post/reducer.ts
> +          [action.id]: action.isLike
아니면 여기도 그냥 increaseLikeCount, decreaseLikeCount로 나눠도 괜찮을듯..ㅋㅋㅋ

2021-08-21 04:14 UTC, loftol commented on client/src/redux/post/type.ts
> +}
그렇게 중요하진 않을 수도 있는데,
배열을 쓰면 저번에도 말했듯이 filter등의 작업을 추가해야 하고 그러면 배열 전체를 탐색하게 될 거 같아.
(내부 구현이 iterator를 통해서 전부다 돌면서 비교하는 식이니까)
좋아요 버튼을 누를때만 작동하는 함수면 딱히 신경 안 쓰겠지만 아무래도 글을 부를 때마다 호출하는 함수라서
0.1초라도 더 빨랐으면 좋겠다는 마음으로 key:value쌍으로 저장을 했습니다..
(사실 이건 정확히는 모르겠는게 c++에서 map처럼 구현되어 있는 거면 해시 함수로 구현됐을 거고 이러면 상수 시간 복잡도 일텐데 혹시 key를 일일이 비교하는 거면 뭐..)

local storage를 보는 사람 입장에서도 liked{7:true} 라는 식으로 보이면 좀 더 눈에 잘 보일거라고도 생각했는데
네가 보기에 이 정도의 시간은 딱히 무시해도 될만한 값이라고 여겨지고
코드가 복잡해지는 거 (아마 ClapBox의 useEffect 내부?) 가 더 문제된다고 생각한다면 바로 고칠게

사실 배열 구현을 먼저 했었어서 그거 바꾸는 건 금방 할거야

2021-08-21 06:28 UTC, loftol commented on server/src/graphql/post.ts
> +      }
이거 해보니까 제작환경이라 그런지는 몰라도 하트 누르고 숫자 바뀌는데 눈에 띄게 느려져서 (거의 0.3초 정도는 걸리는 듯)
여러명이 한 포스트에 동시접속 한 상태로 각각 좋아요를 누르는 상황에 꼭 2 오르는 게 필요한 부분이라면 어쩔 수 없겠지만 아니라면 되도록이면 놔두고 싶은데..

2021-08-21 13:46 UTC, Ikalli commented on client/src/redux/post/type.ts
> +}
음.. 사실 시간복잡도가 막 중요하다거나 그런 문제는 아닐거같고..
일단 로컬스토리지는 익명의 유저가 들여다볼 일은 없어야하는데ㅋㅋ

문제점을 꼽자면
1. 만약 유저가 id가 1인 글을 좋아요 했다가 취소하면, {1: false} 라는 값이 남아있으면 굉장히 좋지 않다고 봄. 그냥 없애버리면 좋은데.. 이런 push, delete에 적합한게 배열이라고 생각함
2. 일단 글에대한 좋아요를 꼭 key-value로 저장해야하는지는 의문임. 시간복잡도가 좀 좋아질진 몰라도 굉장히 미미할거고, 오히려 공간복잡도를 늘릴 수 있다는걸 고려해야 할거같음
3. 아니면 있는지 없는지 검사할 때 시간복잡도가 걱정된다면, 적절한 Set 자료구조를 JS에서 지원해줌https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Set

2021-08-22 10:59 UTC, loftol commented on client/src/components/pages/post/ClapBox.tsx
> +  }, [likeCount]);
연타 방지를 위해서 어쩔 수 없이 useEffect에 그대로 뒀습니다

2021-08-22 11:00 UTC, loftol commented on client/src/components/pages/post/ClapBox.tsx
> +  }
서버 response로 받아오면 속도가 느려져서.. 일단은 그대로 냅뒀습니다. 당장 눈에는 남이 올린 건 안보일 테지만 나중에 새로고침하면 한번에 올라가긴 할거에요.

2021-08-22 11:05 UTC, loftol commented
![likey_4](https://user-images.githubusercontent.com/60003939/130352750-108a3cb8-1486-4200-adaf-630bac09eb1d.gif)
코드를 보면 알겠지만 클릭 후 1초간 아예 클릭을 못하게 막아버림
그 밖에 이것저것 요청하신 대로 바꿔 드렸습니다 ^^

2021-08-22 14:30 UTC, Ikalli requested changes

2021-08-22 14:30 UTC, Ikalli commented on client/src/redux/post/reducer.ts
> +};
```ts
export const initialPostState: PostState = {
  likedIds: number[]
};
```
로 쓰면 될거같음

2021-08-22 14:30 UTC, Ikalli commented on client/src/components/pages/post/ClapBox.tsx
> +  const [like, setLike] = useState(false);
`likeIds`를 이용해 지연 state 초기화 해주는게 좋을듯
예를들면, 유저가 좋아요 클릭한 글 갔을 때 처음엔 false였다가 true로 바뀌니까 useEffect안에 쿼리문 들어갔다면 쿼리 호출하게 되서 버그가 걸릴듯...

2021-08-22 14:30 UTC, Ikalli commented on client/src/components/pages/post/ClapBox.tsx
> +  }, [running]); //의존 변수로는 running만 넣으면 된다. (따라서 running의 초깃값은 false이다.)
좀 난해한거 같은데, lodash모듈의 debounce를 쓰면 해결될거같은데...

```ts
const debouncedClick = debounce(() => setLike(!like), 1000)

useEffect(() => {
  // 쿼리 호출
}, [like])

<button onClick={debouncedClick} />
```

2021-08-22 14:35 UTC, Ikalli commented on client/src/components/pages/post/ClapBox.tsx
> +  }, [running]); //의존 변수로는 running만 넣으면 된다. (따라서 running의 초깃값은 false이다.)
throttle로 정정할게용

2021-08-28 09:35 UTC, loftol commented on client/src/components/pages/post/ClapBox.tsx
> +  }, [running]); //의존 변수로는 running만 넣으면 된다. (따라서 running의 초깃값은 false이다.)
throttle로 했을 때 새로 고침 시 발생하는 버그 때문에 그냥 처음 쓴 대로 유지할게요.
대신 useEffect내부에서 setTimeout을 사용하지 않고 query가 끝나는 대로 입력을 받을 수 있게 수정했습니다.
running 변수는 useRef를 사용해서 refObject로 바꾼 덕에 코드 자체는 더 간결해졌다고 생각합니다.

2021-08-28 14:48 UTC, Ikalli requested changes

2021-08-28 14:48 UTC, Ikalli commented on server/src/graphql/post.ts
> +        const [editPost] = await Promise.all([PostModel.findById(args.id)]);
불필요한 Promise.all()... 없애도 될듯

2021-08-28 14:50 UTC, Ikalli commented on server/src/graphql/post.ts
> +        const [editPost] = await Promise.all([PostModel.findById(args.id)]);
완료되면 merge!

2021-08-28 16:29 UTC, merged