Post page
lumyjuwon/elaina-blog pull request #32
Opened 2021-09-05 15:39 UTC by loftol

![next_prev_button](https://user-images.githubusercontent.com/60003939/132132494-d1a8bc9b-fbc4-48fe-9b52-59fe837c1f59.PNG)
사실 완전 PR을 하고 싶어서  PR을 올린 건 아니고 일단 적당히 올린 다음에 디자인 같은 거 세세하게 조정해줬으면 좋겠어서 올려둠.

추가로 theme부분에 뭐 추가하려다 열 받아서 사전 순으로 정렬해버렸고

다중 클릭 막는 버튼 컴포넌트 만들어서 댓글 여러 개 입력되는 것도 막히는 거 잘 확인 했어.
코드 보면 해당 tsx파일에 설명도 자세하게 써 놨으니 쓸만하다 싶으면 가져다 쓰면 될 듯

2021-09-07 13:31 UTC, Ikalli requested changes
굳굳 디자인도 좋네용👍
다만 댓글 윗쪽으로 옮기는게 더 좋아보일듯!

2021-09-07 13:31 UTC, Ikalli commented on client/src/components/common/button/SubmitButton.tsx
> +(nextFunction이 없으면 이 컴포넌트를 안 쓰는게 맞습니다.)
자꾸 이런 방식을 고집하는것 같은데..
setState와 mutation을 뗄 수 없는 사이라고 생각하면 될듯

왜 먼저 setState를 하는건지...?
아래와 같은 상황이 생길수도 있는데...
1. 만약 mutation도중 에러(혹은 버그)가 난다면?
2. mutation 응답으로 에러값이 온다면?
3. 사용자 인증(Authentication)이 완료되지 않았는데도 댓글, 답글을 쓸 수 있는건가?(state 가 먼저 바뀌니까)
4. 마이너 한 걸수도 있지만, 만약 서버가 중간에 다운됬다면?

prev, next를 나누는게 좋지 않아보임. 그냥 submit 할 때 호출할 핸들링 함수를 받아서 그걸 실행시키면 되는거 아닌가?
```ts
handleSubmit: () => Promise<void>;
```

2021-09-07 13:31 UTC, Ikalli commented on client/src/components/common/button/SubmitButton.tsx
> +(nextFunction이 없으면 이 컴포넌트를 안 쓰는게 맞습니다.)
서버, 클라이언트가 2-way communication을 한다고 생각하면 좋을듯
클라에서 요청(Request) -> 서버에서 요청 처리 -> 처리한 요청에 대한 서버의 응답(Response) -> 서버에서 응답 받아서, 에러 처리 후(에러가 있다면) state changes

2021-09-07 13:31 UTC, Ikalli commented on client/src/components/pages/post/SimplePostItem.tsx
> +};
`interface Direction`, `export const Direction` 이름이 겹치는디...?
그리고 변수명은 `camelCase`!

2021-09-07 13:31 UTC, Ikalli commented on client/src/components/pages/post/SimplePostItem.tsx
> +};
스타일 관련 props는 리액트 단에서 받지 않는걸로!
몰론 방향같은 정보는 받을 수 있지만, 정말 raw한 css는 받지 않게 합시당. 아까 enum에 올린 리뷰랑 연관되어 있는 컴포넌트인 것 같음

2021-09-07 13:31 UTC, Ikalli commented on client/src/components/pages/post/comment/writer/Writer.tsx
> +        </SubmitButton>
SubmitButton 컴포넌트가 시간을 받는다는게 뭔가 조잡한 느낌? 그냥 promise 처리가 완료되면 버튼이 활성화 되도 크게 문제될 게 없어보임

2021-09-07 13:31 UTC, Ikalli commented on client/src/pages/post/[pid]/index.tsx
> +    const nextPost = nextPostQueryResult.data.getNextPost;
프로미스의 응답을 기다렸다가, 이후 프로미스나 로직에 사용될 게 아니면, `Promise.all()`로 병렬처리하는게 속도에서 훨씬 좋음.
지금상황을 예를들면
1. 프로필 정보(가져올때 까지 기다림) .3초
2. prevPost (가져올때까지 기다림) .5초
3. nextPost (가져올때까지 기다림) . 5초

총 1.3초걸리는데, 이를 병렬처리하면 .5초에 다 끝낼수 있음

2021-09-07 13:31 UTC, Ikalli commented on server/src/graphql/post.ts
> +        const posts = await PostModel.find({ _id: { $lt: args.hereId }, categoryId: herePost?.categoryId }, {}, { sort: { _id: -1 } });
```ts
const herePost = await PostModel.findOne({ _id: args.hereId });
```
herePost가 null이면 에러를 던지는게 더 좋을 것 같음
`throw new ApolloError("Error: post not found")`


null check를 하지 않으면 다음 라인의 `categoryId: herePost?.categoryId`에서 에러가 날 것 같은데?

2021-09-07 13:31 UTC, Ikalli commented on server/src/graphql/post.ts
> +        const posts = await PostModel.find({ _id: { $lt: args.hereId }, categoryId: herePost?.categoryId }, {}, { sort: { _id: -1 } });
`find`보단 `findOne`이 문맥상 맞지 않을까? 이전, 이후 포스트는 최대 1개만 나오면 되니까

2021-09-07 14:36 UTC, loftol commented on client/src/components/common/button/SubmitButton.tsx
> +(nextFunction이 없으면 이 컴포넌트를 안 쓰는게 맞습니다.)
사용자 인증이 완료되지 않고 댓글, 답글이 써지는가 하는 건 분명히 아니라고 말할 수 있어.
저기서 발생되는 setState같은 경우에는 useEffect를 발생 시키기 위한 트리거 정도고
함수를 쭉 따라가보면 mutation을 호출하는 함수 이후에 댓글, 답글에 대한 state를 변경 시키기 때문에
버튼 컴포넌트에 들어있는 useEffect가 완전히 끝난 이후에 자동으로 다시 렌더링 되는 구조야.

그러니까 정확히는
setRunning으로 running state가 변화함 => render => running에 의한 useEffect실행
=> useEffect에 의해 nextFunction실행 => nextFunction 내부 mutation 실행 (댓글,답글의 서버통신)
=> mutation 종료 후 해당 컴포넌트 state 변경이 실행됨 => ...
이런 순서로 진행될거야.

네가 걱정하는 일은 일어나지 않겠지만.. 확실히 최적화는 필요할거라고 생각해

2021-09-07 14:39 UTC, loftol commented on client/src/components/pages/post/BoxDesigns.tsx
> +}
이건 확실히 내 욕심이라 바로 고칠게요.. 최대한 컴포넌트 내부를 간단하게 보이고 싶었는데 영 좋지 못했던 듯..
그냥 direction 정보만 넘겨받은 다음에 삼항연산자로 다 처리하면 아마 문제 없을 것 같아

2021-09-09 17:09 UTC, loftol commented on server/src/graphql/post.ts
> +        const posts = await PostModel.find({ _id: { $lt: args.hereId }, categoryId: herePost?.categoryId }, {}, { sort: { _id: -1 } });
이거 없는 경우에 error처리를 하기에는 그냥 다음이나 이전포스트가 없을때 마저도 에러가 나는 거라 좀 그렇긴 해
그리고 당장은 null이 뜰만한 상황에서도 에러가 나지는 않더라고
정말 필요하겠다고 말해주면 빈 포스트를 만들어서 예외처리를 할텐데 안그래도 될거같으면 그냥 놔둘게

2021-09-10 00:12 UTC, Ikalli commented on server/src/graphql/post.ts
> +        const posts = await PostModel.find({ _id: { $lt: args.hereId }, categoryId: herePost?.categoryId }, {}, { sort: { _id: -1 } });
음.. 내가말한건 `herePost`가 없을 때 에러를 처리하는거였는대.. 뭐 그럴경우는 흔치 않겠지만ㅋㅋ

2021-09-10 00:23 UTC, Ikalli commented on client/src/components/common/button/SubmitButton.tsx
> +(nextFunction이 없으면 이 컴포넌트를 안 쓰는게 맞습니다.)
실행 순서는 맞지만, useEffect내부를 보면 next 응답을 보지 않고 state변경을 해버리는대.. `props.nextFunction`이 무조건 성곤하는 쿼리는 아니니깐 ㅋㅋ 응답에 대한 처리도 들어가있으면 완벽하지 않을까?

2021-09-27 12:13 UTC, merged